<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Crie sua conta — ClientLoop</title><link rel="icon" type="image/png" href="{{ asset('images/clientloop-symbol.png') }}">
    <style>:root{--ink:#172033;--muted:#607089;--brand:#0f766e;--line:#d7e2e0}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#f2f8f7;color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;display:grid;grid-template-columns:42% 58%}.aside{background:#123d39;color:#fff;padding:clamp(34px,7vw,96px);display:flex;flex-direction:column;justify-content:space-between}.brand{display:inline-flex;align-items:center;gap:.55rem;color:#fff;text-decoration:none;font-size:1.35rem;font-weight:800;letter-spacing:-.04em}.brand-mark{width:2rem;height:2rem}.brand span{color:#7dd3c7}.aside h1{font-size:clamp(2.1rem,4vw,3.5rem);line-height:1.05;letter-spacing:-.05em;margin:0}.aside p,.bullets{color:#c3ddd8;max-width:380px}.bullets{padding:0;list-style:none}.bullets li{margin:14px 0}.bullets li:before{content:"✓";color:#7dd3c7;font-weight:800;margin-right:10px}.form-area{display:grid;place-items:center;padding:36px}.card{width:min(470px,100%)}h2{font-size:2rem;letter-spacing:-.04em;margin:0 0 8px}.intro{color:var(--muted);margin:0 0 26px}label{display:block;font-size:.9rem;font-weight:700;margin:16px 0 6px}input{width:100%;border:1px solid var(--line);border-radius:9px;background:#fff;padding:12px 13px;font:inherit;outline-color:var(--brand)}button{width:100%;margin-top:25px;border:0;border-radius:9px;background:var(--brand);color:#fff;padding:13px;font:inherit;font-weight:800;cursor:pointer}.error{background:#fff0f0;color:#b42318;padding:11px 13px;border-radius:8px;font-size:.9rem}.signin{margin-top:22px;text-align:center;color:var(--muted);font-size:.92rem}.signin a{color:var(--brand);font-weight:700;text-decoration:none}@media(max-width:800px){body{display:block}.aside{min-height:280px;padding:32px}.aside h1{font-size:2.2rem}.bullets{display:none}.form-area{padding:38px 24px}}</style>
</head>
<body>
    <aside class="aside"><a class="brand" href="{{ route('home') }}"><img class="brand-mark" src="{{ asset('images/clientloop-symbol.png') }}" alt="">Client<span>Loop</span></a><div><h1>Organize a rotina do seu pet shop.</h1><p>Crie seu ambiente para controlar agenda, pets, responsáveis e pacotes.</p></div><ul class="bullets"><li>Empresa e dados isolados</li><li>Agenda, confirmações e pacotes</li><li>Cadastro inicial em poucos minutos</li></ul></aside>
    <main class="form-area"><section class="card"><h2>Crie sua conta</h2><p class="intro">Comece configurando a empresa e o usuário responsável.</p><form method="post" action="{{ route('register.store') }}">@csrf<label for="company_name">Nome da empresa</label><input id="company_name" name="company_name" value="{{ old('company_name') }}" required autofocus><label for="name">Seu nome</label><input id="name" name="name" value="{{ old('name') }}" required><label for="email">E-mail de trabalho</label><input id="email" type="email" name="email" value="{{ old('email') }}" required><label for="password">Senha</label><input id="password" type="password" name="password" minlength="12" required><label for="password_confirmation">Confirme a senha</label><input id="password_confirmation" type="password" name="password_confirmation" minlength="12" required>@if($errors->any())<p class="error">{{ $errors->first() }}</p>@endif<button type="submit">Criar conta e continuar</button></form><p class="signin">Já tem uma conta? <a href="{{ url('/admin/login') }}">Entrar no ClientLoop</a></p></section></main>
</body>
</html>
